name: Generate Datas

on:
  schedule:
    - cron: "0 */12 * * *" # Executa a cada 12 horas
  workflow_dispatch:

jobs:
  build:
    name: Update Contributions Snake
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      # Gera a animação da cobrinha
      - name: Gerar Snake SVG
        uses: Platane/snk@master
        with:
          github_user_name: PatrickDSants
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      # Publica a animação no GitHub Pages
      - name: Publicar no GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


